// __tests__/helpers/lab-public.js
// Public Endpoint Lab files for tests: __tests__/fixtures/lab-public is real exporter output (generated by
// `WEB_SAMPLE_OUT=<dir> python -m unittest test_endpoint_lab.WebExportTests.test_write_contract_sample_for_the_website`
// in deploy/endpoint-lab of the feat/endpoint-lab branch). The Lab test clock is fixed, so every ISO timestamp is shifted to "now".

'use strict';

const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');

const FIXTURE_DIR = path.join(__dirname, '..', 'fixtures', 'lab-public');
const ISO_RE = /^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}Z$/;

const shiftIso = (value, deltaMs) => {
  if (typeof value === 'string' && ISO_RE.test(value)) {
    return new Date(Date.parse(value) + deltaMs).toISOString().replace('.000Z', 'Z');
  }
  if (Array.isArray(value)) return value.map((v) => shiftIso(v, deltaMs));
  if (value && typeof value === 'object') {
    return Object.fromEntries(Object.entries(value).map(([k, v]) => [k, shiftIso(v, deltaMs)]));
  }
  return value;
};

const readFixture = (rel) => JSON.parse(fs.readFileSync(path.join(FIXTURE_DIR, rel), 'utf8'));

/**
 * Writes the fixture into `dir`, timestamps moved so that the export happened `ageMs` ago.
 * @param {string} dir
 * @param {{ mode?: 'full' | 'compat', ageMs?: number, now?: number }} [opts]
 */
const writeLabPublic = (dir, { mode = 'full', ageMs = 20e3, now = Date.now() } = {}) => {
  const generatedAt = Date.parse(readFixture('web-overview.json').generatedAt);
  const delta = Math.round((now - ageMs - generatedAt) / 1000) * 1000;
  fs.rmSync(dir, { recursive: true, force: true });
  fs.mkdirSync(dir, { recursive: true });
  const put = (rel, doc) => fs.writeFileSync(path.join(dir, rel), `${JSON.stringify(shiftIso(doc, delta))}\n`);
  put('active-pool.json', readFixture('active-pool.json'));
  put('lab-status.json', readFixture('lab-status.json'));
  if (mode === 'full') {
    put('web-overview.json', readFixture('web-overview.json'));
    fs.mkdirSync(path.join(dir, 'web-endpoints'));
    for (const name of fs.readdirSync(path.join(FIXTURE_DIR, 'web-endpoints'))) {
      put(path.join('web-endpoints', name), readFixture(path.join('web-endpoints', name)));
    }
  }
  return dir;
};

const tempLabDir = () => fs.mkdtempSync(path.join(os.tmpdir(), 'awg-lab-public-'));

/** Every key and string of a JSON value, for "nothing secret leaves the API" checks. */
const flatten = (value, out = []) => {
  if (Array.isArray(value)) value.forEach((v) => flatten(v, out));
  else if (value && typeof value === 'object') {
    for (const [k, v] of Object.entries(value)) {
      out.push(k);
      flatten(v, out);
    }
  } else if (typeof value === 'string') out.push(value);
  return out;
};

module.exports = { FIXTURE_DIR, writeLabPublic, tempLabDir, readFixture, flatten };
